import assert from 'node:assert/strict';
import { mkdir, writeFile } from 'node:fs/promises';
import { homedir } from 'node:os';
import { join } from 'node:path';
import { pathToFileURL } from 'node:url';

const plugin = join(homedir(), '.config', 'opencode', 'plugins', 'jobs');
const { request, call } = await import(pathToFileURL(join(plugin, 'src', 'bridge.js')));
const { stateDirectory } = await import(pathToFileURL(join(plugin, 'src', 'paths.js')));
const unwrap = (value) => value?.data ?? value;
const info = await request('/api/info');
assert.equal(info.version, '2.0.22');
const plugins = unwrap(await request('/api/plugin', { directory: homedir() }));
assert.ok(plugins.some((item) => item.id === 'opencode.jobs' && item.state.status === 'active' && item.features.tui));
const commands = unwrap(await request('/api/command', { directory: homedir() }));
for (const name of ['background', 'monitor', 'loop', 'schedule', 'jobs', 'cancel']) assert.ok(commands.some((item) => item.name === name));
const directory = join(stateDirectory(), 'verification');
await mkdir(directory, { recursive: true, mode: 0o700 });
const session = unwrap(await request('/api/session', { method: 'POST', body: { title: 'OpenCode jobs installation verification', location: { directory } } }));
const sessionID = session.id;
const before = await call('list', { sessionID });
assert.ok(before.healthy);
assert.equal(before.jobs.length, 0);
const schedule = await call('create', { sessionID, name: 'schedule', raw: 'in 5m Проверочное задание; отменить до исполнения.' });
const loop = await call('create', { sessionID, name: 'loop', raw: '5m Проверочное задание; отменить до исполнения.' });
await call('cancel', { sessionID, id: schedule.job.id });
await call('cancel', { sessionID, id: loop.job.id });
assert.ok((await call('list', { sessionID })).jobs.every((job) => job.status === 'cancelled'));
const result = { ok: true, platform: process.platform, version: info.version, serverPID: info.pid, sessionID, commands: 6, checks: ['active plugin and TUI entrypoint', 'healthy pump', 'node-local session isolation', 'schedule create/cancel', 'loop create/cancel'], modelRequests: 0 };
await writeFile(join(stateDirectory(), 'verification.json'), JSON.stringify(result, null, 2), { mode: 0o600 });
process.stdout.write(JSON.stringify(result) + '\n');
